### ISSUE TITLE
linkar a maquina do cliente com o render.com

### ISSUE THREAD

**Issue by Malbuq** [RonyRangelSS/jsp-servlet-baseapp#6]

**Comment by Malbuq** [comment]
tentando fazer isso

**Comment by RonyRangelSS** [comment]
acho que consegui fazer isso.

**Comment by Malbuq** [comment]
dá pra upar as coisas da main e agora altera lá?

**Comment by RonyRangelSS** [comment]
não testei ainda

**Comment by RonyRangelSS** [comment]
tenta fazer aí mesmo. depois dá o feedback

**Comment by Malbuq** [comment]
acho q n consigo pq n sou o dono do repo

**Comment by RonyRangelSS** [comment]
pode deixar então

**Comment by RonyRangelSS** [comment]
tenta ver o actions
